//
export const GET_ALL_PROFILES = "GET_ALL_PROFILES";
export const CLEAR_ALL_PROFILES = "CLEAR_ALL_PROFILES";
export const ALL_PROFILES_ERROR = "ALL_PROFILES_ERROR";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

export const AUTH_SIGN_UP = "AUTH_SIGN_UP";
export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const AUTH_SIGN_UP_ERROR = "AUTH_SIGN_UP_ERROR";
export const AUTH_SIGN_IN_ERROR = "AUTH_SIGN_IN_ERROR";
export const CLEAR_PROFILES = "CLEAR_PROFILES";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_ERRORS = "PROFILE_ERRORS";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_ERRORS = "PRODUCT_ERRORS";
export const LISTING_ERRORS = "LISTING_ERRORS";
export const LIST_PRODUCT_FOR_CROWDFUNDING = "LIST_PRODUCT_FOR_CROWDFUNDING";
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const CURRENT_PROFILE_ERRORS = "CURRENT_PROFILE_ERRORS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SHOW_DISPLAY_PROFILE = "SHOW_DISPLAY_PROFILE";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CATEGORY_FILTER_PRODUCTS = "CATEGORY_FILTER_PRODUCTS";
export const LIST_CROWD_FUND_ITEMS = "LIST_CROWD_FUND_ITEMS";
export const LIST_CROWD_FUND_ITEMS_FOR_DISPLAY_PROFILE =
  "LIST_CROWD_FUND_ITEMS_FOR_DISPLAY_PROFILE";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PROFILE_FORM_SUBMIT = "PROFILE_FORM_SUBMIT";
export const DELETE_CROWDFUNDED_ITEM = "DELETE_CROWDFUNDED_ITEM";
